<?

$tpl_vars = array(
	"label"     => array(
		"class"  => "base::header",
		"name" => "blocks",
		"value" => "Шаблон страницы для составления из блоков",
	),

	"title"      => array(
		"class" => "base::textbox",
		"prompt" => Dreamedit::translate("Title Russian"),
		"size" => "51",
		"field" => "title",
		"buttons" => "quot",
	),
	"title_en"      => array(
		"class" => "base::textbox",
		"prompt" => Dreamedit::translate("Title English"),
		"size" => "51",
		"field" => "title_en",
		"buttons" => "quot",
	),
	"description"   => array(
		"class" => "base::textarea",
		"prompt" => Dreamedit::translate("Description"),
		"field" => "description",
		"cols" => "51",
		"rows" => "5",
	),
	"keywords"   => array(
		"class" => "base::textarea",
		"prompt" => Dreamedit::translate("Keywords"),
		"cols" => "51",
		"rows" => "5",
		"field" => "keywords",
	),
    "left_collumn"      => array(
        "class" => "base::selectHeader",
        "prompt" => Dreamedit::translate("Левая колонка"),
        "field" => "left_collumn",
    ),
    "right_collumn"      => array(
        "class" => "base::selectHeader",
        "prompt" => Dreamedit::translate("Правая колонка"),
        "field" => "right_collumn",
    ),
    "wide_sections" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Расширяемые блоки"),
        "value" => "0",
        "options" => "",
        "field" => "wide_sections",
    ),
    "no_menu" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Отключить меню"),
        "value" => "0",
        "options" => "",
        "field" => "no_menu",
    ),
    "no_gray_menu" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Отключить серое меню"),
        "value" => "0",
        "options" => "",
        "field" => "no_gray_menu",
    ),
    "right_block_back_off" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Отключить подложку в правых блоках"),
        "help" => 'Если страница с обычным шаблоном, то там не будет выводится белая подложка',
        "value" => "0",
        "options" => "",
        "field" => "right_block_back_off",
    ),
    "like_main" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Блоки как на главной"),
        "help" => 'Блоки берутся из левой колонки',
        "value" => "0",
        "options" => "",
        "field" => "like_main",
    ),
    "left_block_custom_size"     => array(
        "class" => "base::selectbox",
        "prompt" => Dreamedit::translate("Размер левого блока"),
        "options" => array('' => '', '2' => '2','3' => '3','4' => '4','5' => '5','6' => '6','7' => '7','8' => '8','9' => '9','10' => '10'),
        "field" => "left_block_custom_size",
    ),
    "mag_header" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Шапка с кастомным меню"),
        "value" => "1",
        "options" => "",
        "field" => "mag_header",
    ),
    "add_menu_on" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Включить доп. меню"),
        "value" => "0",
        "options" => "",
        "field" => "add_menu_on",
    ),
    "add_menu_size_w"      => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Размер подменю"),
        "size" => "5",
        "field" => "add_menu_size_w",
    ),
    "add_menu_left_size_w"      => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Размер левой колонки подменю"),
        "size" => "5",
        "field" => "add_menu_left_size_w",
    ),
    "english_off" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Отключить переход на английскую версию"),
        "options" => "",
        "field" => "english_off",
    ),
    "custom_logo"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Кастомный логотип"),
        "field" => "custom_logo",
    ),
    "custom_logo_s"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Кастомный логотип для мобильных"),
        "field" => "custom_logo_s",
    ),
    "custom_logo_w"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("Ширина кастомного логотипа"),
        "size" => "5",
        "field" => "custom_logo_w",
    ),
    "custom_logo_s_w"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("Ширина кастомного логотипа для мобильных"),
        "size" => "5",
        "field" => "custom_logo_s_w",
    ),
    "bottom_id_link"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("Поля подвала со страницы"),
        "size" => "10",
        "field" => "bottom_id_link",
        "buttons" => "page_id",
        "help" => "Если выбрана страница(например главная с полями подвала) то подвал будет с этой страницы",
    ),
    "fc_first"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал первая колонка"),
        "field" => "fc_first",
        "type" => "Default",
    ),
    "fc_second"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал вторая колонка"),
        "field" => "fc_second",
        "type" => "Default",
    ),
    "fc_third"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал третья колонка"),
        "field" => "fc_third",
        "type" => "Default",
    ),
    "footer_copyright"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал копирайт"),
        "field" => "footer_copyright",
        "type" => "Default",
    ),
    "fc_first_en"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал первая колонка (En)"),
        "field" => "fc_first_en",
        "type" => "Default",
    ),
    "fc_second_en"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал вторая колонка (En)"),
        "field" => "fc_second_en",
        "type" => "Default",
    ),
    "fc_third_en"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал третья колонка (En)"),
        "field" => "fc_third_en",
        "type" => "Default",
    ),
    "footer_copyright_en"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал копирайт (En)"),
        "field" => "footer_copyright_en",
        "type" => "Default",
    ),
    "main_menu_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID главного меню"),
        "size" => "10",
        "field" => "main_menu_id",
        "buttons" => "page_id",
    ),
    "gray_menu_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID серого меню"),
        "size" => "10",
        "field" => "gray_menu_id",
        "buttons" => "page_id",
    ),
    "footer_slider_off" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Отключить слайдер в подвале"),
        "value" => "0",
        "options" => "",
        "field" => "footer_slider_off",
    ),
    "person"      => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Страница персоны для элементов (ID)"),
        "help" => "Если пусто, то в разных блоках не будет ограничений на персону(выводятся все элементы)",
        "size" => "51",
        "field" => "person",
        "buttons" => "quot",
    ),
);

?>