<?

$tpl_vars = array(
	"label"     => array(
		"class"  => "base::header",
		"name" => "mag_index",
		"value" => "Журналы(Новый модуль). Шаблон главной страницы",
	),
	"title"      => array(
		"class" => "base::textbox",
		"prompt" => Dreamedit::translate("Title Russian"),
		"size" => "51",
		"field" => "title",
		"buttons" => "quot",
	),
	"title_en"      => array(
		"class" => "base::textbox",
		"prompt" => Dreamedit::translate("Title English"),
		"size" => "51",
		"field" => "title_en",
		"buttons" => "quot",
	),
	"description"   => array(
		"class" => "base::textarea",
		"prompt" => Dreamedit::translate("Description"),
		"field" => "description",
		"cols" => "51",
		"rows" => "5",
	),
	"keywords"   => array(
		"class" => "base::textarea",
		"prompt" => Dreamedit::translate("Keywords"),
		"cols" => "51",
		"rows" => "5",
		"field" => "keywords",
	),
    "menuname" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Название краткое"),
        "required" => FALSE,
        "size" => "51",
        "field" => "page_menuname",
    ),
    "menuname_en" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Название краткое (English)"),
        "required" => FALSE,
        "size" => "51",
        "field" => "page_menuname_en",
    ),
    "publisher"   => array(
        "class" => "base::textarea",
        "prompt" => Dreamedit::translate("Издатель"),
        "field" => "publisher",
        "cols" => "51",
        "rows" => "5",
    ),
    "publisher_en"   => array(
        "class" => "base::textarea",
        "prompt" => Dreamedit::translate("Издатель (English)"),
        "field" => "publisher_en",
        "cols" => "51",
        "rows" => "5",
    ),
    "online_resource" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Электронный ресурс"),
        "value" => "0",
        "options" => "",
        "field" => "online_resource",
    ),
    "issn" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("ISSN"),
        "size" => "51",
        "field" => "issn",
    ),
    "crossref_issn" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("ISSN для Crossref печатный"),
        "size" => "51",
        "field" => "crossref_issn",
    ),
    "crossref_issn_electronic" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("ISSN для Crossref электронный"),
        "size" => "51",
        "field" => "crossref_issn_electronic",
    ),
    "crossref_issn_doi" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Текст вместо ISSN для составления DOI"),
        "size" => "51",
        "field" => "crossref_issn_doi",
    ),
    "crossref_abbrev" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Аббревиатура Crossref"),
        "size" => "51",
        "field" => "crossref_abbrev",
    ),
    "crossref_pdf" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Прямые ссылки на PDF для Crossref"),
        "value" => "0",
        "options" => "",
        "field" => "crossref_pdf",
    ),
    "crossref_en" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Английские ссылки для Crossref"),
        "value" => "0",
        "options" => "",
        "field" => "crossref_en",
    ),
    "series" => array(
        "class" => "base::selecttextbox" ,
        "prompt" => Dreamedit::translate("Периодичность"),
        "size" =>"1",
        "field" => "series",
        "texts" => "|Ежемесячный журнал|Ежеквартальный журнал|Бюллетень|Ежеквартальный бюллетень|Ежегодник|Журнал|Ежегодное сетевое издание",
    ),
    "series_en" => array(
        "class" => "base::selecttextbox" ,
        "prompt" => Dreamedit::translate("Периодичность на англ"),
        "size" =>"1",
        "field" => "series_en",
        "texts" => "|Monthly|Quarterly|Bulletin|Yearbook|Journal|Quarterly Bulletin",
    ),
    "numbers" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Количество номеров в год"),
        "size" => "11",
        "field" => "numbers",
    ),
    "logo" => array(
        "class" => "base::editor",
        "type" => "Basic",
        "prompt" => Dreamedit::translate("Обложка 62х"),
        "size" => "51",
        "field" => "logo",
    ),
    "info" => array(
        "class" => "base::editor",
        "type" => "Basic",
        "prompt" => Dreamedit::translate("Краткая информация"),
        "size" => "51",
        "field" => "info",
    ),
    "info_en" => array(
        "class" => "base::editor",
        "type" => "Basic",
        "prompt" => Dreamedit::translate("Краткая информация на английском"),
        "size" => "51",
        "field" => "info_en",
    ),
    "logo_main" => array(
        "class" => "base::editor",
        "type" => "Basic",
        "prompt" => Dreamedit::translate("Обложка на главную"),
        "size" => "51",
        "field" => "logo_main",
    ),
    "logo_main_info" => array(
        "class" => "base::editor",
        "type" => "Full",
        "prompt" => Dreamedit::translate("Информация под обложкой"),
        "size" => "101",
        "field" => "logo_main_info",
    ),
    "logo_main_info_en" => array(
        "class" => "base::editor",
        "type" => "Full",
        "prompt" => Dreamedit::translate("Информация под обложкой (En)"),
        "size" => "101",
        "field" => "logo_main_info_en",
    ),
    "logo_slider" => array(
        "class" => "base::editor",
        "type" => "Basic",
        "prompt" => Dreamedit::translate("Обложка для слайдера"),
        "size" => "51",
        "field" => "logo_slider",
    ),
    "left_collumn_custom" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Кастомная левая колонка"),
        "value" => "0",
        "options" => "",
        "field" => "left_collumn_custom",
    ),
    "left_collumn"      => array(
        "class" => "base::selectHeader",
        "prompt" => Dreamedit::translate("Левая колонка"),
        "field" => "left_collumn",
    ),
    "right_collumn"      => array(
        "class" => "base::selectHeader",
        "prompt" => Dreamedit::translate("Правая колонка"),
        "field" => "right_collumn",
    ),
    "left_block_custom_size"     => array(
        "class" => "base::selectbox",
        "prompt" => Dreamedit::translate("Размер левого блока страниц журнала"),
        "options" => array('' => '', '2' => '2','3' => '3','4' => '4','5' => '5','6' => '6','7' => '7','8' => '8','9' => '9','10' => '10'),
        "field" => "left_block_custom_size",
    ),
    "mag_header" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("Шапка и подвал журналов"),
        "value" => "1",
        "options" => "",
        "field" => "mag_header",
    ),
    "no_prefix" => array(
        "class" => "base::checkbox",
        "prompt" => Dreamedit::translate("№ - как префикс перед номером"),
        "help" => "Если отключить, не будет выводится `№`",
        "value" => "1",
        "options" => "",
        "field" => "no_prefix",
    ),
    "jour_counter"      => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Название для счетчика"),
        "help" => "Изначально давались по адресу журнала. Например \"meimo\". Если пустое - статистика не ведётся.",
        "size" => "51",
        "field" => "jour_counter",
    ),
    "menu_gradient_1" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Цвет меню градиент 1"),
        "size" => "10",
        "field" => "menu_gradient_1",
        "buttons" => "colorpick",
    ),
    "menu_gradient_2" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Цвет меню градиент 2"),
        "size" => "10",
        "field" => "menu_gradient_2",
        "buttons" => "colorpick",
    ),
    "menu_image" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Картинка вместо цвета меню"),
        "size" => "100",
        "help" => "Для примера /files/Images/menu.png",
        "field" => "menu_image",
    ),
    "menu_text_color" => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Цвет текста меню"),
        "size" => "10",
        "field" => "menu_text_color",
        "buttons" => "colorpick",
    ),
    "menu_custom_font"      => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Кастомный шрифт в меню"),
        "size" => "51",
        "field" => "menu_custom_font",
    ),
    "menu_custom_font_size"      => array(
        "class" => "base::textbox",
        "prompt" => Dreamedit::translate("Размер кастомного шрифта в меню"),
        "size" => "51",
        "field" => "menu_custom_font_size",
    ),
    "main_content"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Контент"),
        "field" => "main_content",
    ),
    "main_content_en"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Контент (English)"),
        "field" => "main_content_en",
    ),
    "main_jour_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID главной страницы"),
        "size" => "10",
        "field" => "main_jour_id",
        "buttons" => "page_id",
    ),
    "main_menu_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID главного меню"),
        "size" => "10",
        "field" => "main_menu_id",
        "buttons" => "page_id",
    ),
    "mag_logo"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Логотип"),
        "field" => "mag_logo",
    ),
    "mag_logo_en"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Логотип (En)"),
        "field" => "mag_logo_en",
    ),
    "mag_logo_width"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("Ширина логотипа"),
        "size" => "50",
        "field" => "mag_logo_width",
    ),
    "mag_logo_width_en"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("Ширина логотипа (En)"),
        "size" => "50",
        "field" => "mag_logo_width_en",
    ),
    "search_page_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы для поиска"),
        "size" => "10",
        "field" => "search_page_id",
        "buttons" => "page_id",
    ),
    "gray_menu_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID серого меню"),
        "size" => "10",
        "field" => "gray_menu_id",
        "buttons" => "page_id",
    ),
    "social_directories"     => array(
        "class" => "base::selectDirectoryId",
        "prompt" => Dreamedit::translate("Лента соц. сетей"),
        "field" => "social_directories",
    ),
    "summary_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы с оглавлением"),
        "size" => "10",
        "field" => "summary_id",
        "buttons" => "page_id",
    ),
    "archive_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы архива номеров"),
        "size" => "10",
        "field" => "archive_id",
        "buttons" => "page_id",
    ),
    "art_archive_en_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы архива статей на английском"),
        "size" => "10",
        "field" => "art_archive_en_id",
        "buttons" => "page_id",
    ),
    "authors_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы индекса авторов"),
        "size" => "10",
        "field" => "authors_id",
        "buttons" => "page_id",
    ),
    "author_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы автора (все статьи автора)"),
        "size" => "10",
        "field" => "author_id",
        "buttons" => "page_id",
    ),
    "rubrics_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы индекса рубрик"),
        "size" => "10",
        "field" => "rubrics_id",
        "buttons" => "page_id",
    ),
    "years_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID годового содержания"),
        "size" => "10",
        "field" => "years_id",
        "buttons" => "page_id",
    ),
    "authors_years_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID годового содержания (Авторы)"),
        "size" => "10",
        "field" => "authors_years_id",
        "buttons" => "page_id",
    ),
    "article_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы статьи"),
        "size" => "10",
        "field" => "article_id",
        "buttons" => "page_id",
    ),
    "rubric_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы Рубрики (статьи в рубрике)"),
        "size" => "10",
        "field" => "rubric_id",
        "buttons" => "page_id",
    ),
    "send_article_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID страницы для отправки статьи"),
        "size" => "10",
        "field" => "send_article_id",
        "buttons" => "page_id",
    ),
    "old_magazine_id"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("ID журнала в старом модуле журналов"),
        "size" => "10",
        "field" => "old_magazine_id",
    ),
    "bottom_id_link"     => array(
        "class" => "base::integer",
        "prompt" => Dreamedit::translate("Поля подвала со страницы"),
        "size" => "10",
        "field" => "bottom_id_link",
        "buttons" => "page_id",
        "help" => "Если выбрана страница(например главная с полями подвала) то подвал будет с этой страницы",
    ),
    "fc_first"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал первая колонка"),
        "field" => "fc_first",
        "type" => "Default",
    ),
    "fc_second"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал вторая колонка"),
        "field" => "fc_second",
        "type" => "Default",
    ),
    "fc_first_en"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал первая колонка (En)"),
        "field" => "fc_first_en",
        "type" => "Default",
    ),
    "fc_second_en"    => array(
        "class" => "base::editor",
        "prompt" => Dreamedit::translate("Подвал вторая колонка (En)"),
        "field" => "fc_second_en",
        "type" => "Default",
    ),
);

?>