<?

$mod_array = array(
	"name"			=> "data_form",
	"template_dir"	=> "plain_table",
	"language"		=> "ru",
	"action"		=> "",
	"components"	=> array (
		"id"		=> array (
			"class"				=> "base::hidden",
			"field"				=> "page_id",
		),
		"parent" => array(
			"class" => "base::integer",
			"prompt" => Dreamedit::translate("Внутри"),
			"value" => (int)@$_REQUEST["id"],
			"field" => "page_parent",
			"size" => "10",
			"buttons" => "page_id",
		),
		"name" => array(
			"class" => "base::textbox",
			"prompt" => Dreamedit::translate("Название"),
			"required" => TRUE,
			"size" => "51",
			"field" => "page_name",
			"buttons"=>"quot",
		),
		"name_en" => array(
			"class" => "base::textbox",
			"prompt" => Dreamedit::translate("Название (English)"),
			"size" => "51",
			"field" => "page_name_en",
			"buttons"=>"quot",
		),
		"urlname" => array(
			"class" => "base::textbox",
			"prompt" => Dreamedit::translate("Адрес страницы"),
			"size" => "101",
			"field" => "page_urlname",
            "buttons" => "generator",
            "generate_fields" => array("name_en", "name"),
		),
		"link" => array(
			"class" => "base::textbox",
			"prompt" => Dreamedit::translate("Ссылка"),
			"size" => "51",
			"field" => "page_link",
			"buttons" => "page_id",
		),
        "link_en" => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Ссылка (English)"),
            "size" => "51",
            "field" => "page_link_en",
            "buttons" => "page_id",
        ),
		"rightblock" => array(
			"class" => "base::textbox",
			"prompt" => Dreamedit::translate("Правый блок"),
			"size" => "51",
			"field" => "rightblock",
		),
		"noright" => array(
			"class" => "base::checkbox",
			"prompt" => Dreamedit::translate("Убрать правый блок"),
			"value" => "0",
			"options" => "",
			"field" => "noright",
		),
        "mobile_right_totop" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Правый блок наверх на мобильной"),
            "value" => "0",
            "options" => "",
            "field" => "mobile_right_totop",
        ),
        "blank" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Ссылка из меню<br>открывается в новом окне"),
            "value" => "0",
            "options" => "",
            "field" => "blank",
        ),
        "title_uppercase" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Заглавные буквы в заголовке"),
            "value" => "0",
            "options" => "",
            "field" => "title_uppercase",
        ),
        "noprint" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Убрать кнопку печать"),
            "value" => "0",
            "options" => "",
            "field" => "noprint",
        ),
        "notop" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Убрать титул и кнопку печать"),
            "value" => "0",
            "options" => "",
            "field" => "notop",
        ),
        "nobreadcrumbs" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Убрать хлебные крошки"),
            "value" => "0",
            "options" => "",
            "field" => "nobreadcrumbs",
        ),
        "nocomment" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Убрать комментарии"),
            "value" => "0",
            "options" => "",
            "field" => "nocomment",
        ),
        "activatestat" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Включить статистику"),
            "value" => "0",
            "options" => "",
            "field" => "activatestat",
        ),
        "archive_material" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Архивный материал"),
            "value" => "0",
            "options" => "",
            "field" => "archive_material",
        ),
        "noactivemenulink" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Отключить ссылку в меню"),
            "value" => "0",
            "options" => "",
            "help" => "Элемент остается в меню, но становится не активным(ссылка не работает)",
            "field" => "noactivemenulink",
        ),
        "notshowmenu" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Не показывать в меню"),
            "value" => "0",
            "options" => "",
            "help" => "Отключить элемент в меню совсем",
            "field" => "notshowmenu",
        ),
        "addmenu" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Вынести в доп. меню"),
            "value" => "0",
            "options" => "",
            "field" => "addmenu",
        ),
        "addmenuleft" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Подменю раскрывается влево"),
            "value" => "0",
            "options" => "",
            "field" => "addmenuleft",
        ),
        "notshowchilds" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Не показывать доп. меню"),
            "help" => "Не выводить элементы в доп. меню",
            "value" => "0",
            "options" => "",
            "field" => "notshowchilds",
        ),
        "submenu_page_capitalize" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Заглавные буквы в списке страниц"),
            "help" => "Заглавные буквы в автоматическом списке страниц на пустой родительской странице",
            "value" => "0",
            "options" => "",
            "field" => "submenu_page_capitalize",
        ),
        "submenu_bold" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Жирные буквы в списке страниц"),
            "value" => "0",
            "options" => "",
            "field" => "submenu_bold",
        ),
        "menu_bold" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Жирные буквы в меню"),
            "value" => "0",
            "options" => "",
            "field" => "menu_bold",
        ),
        "list_color" => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Цвет ссылок в списке страниц"),
            "size" => "10",
            "field" => "list_color",
            "buttons" => "colorpick",
        ),
        "menu_color" => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Цвет ссылок в меню"),
            "size" => "10",
            "field" => "menu_color",
            "buttons" => "colorpick",
        ),
        "addmenucollumn" => array(
            "class" => "base::selectbox",
            "prompt" => Dreamedit::translate("Коллонка в подменю"),
            "value" => "1",
            "options" => array("1" => "1","2" => "2","3" => "3"),
            "field" => "addmenucollumn",
        ),
        "addmenusize" => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Размер подменю(px)"),
            "size" => "51",
            "field" => "addmenusize",
        ),
		"template" => array(
			"class" => "base::selectbox",
			"prompt" => Dreamedit::translate("Шаблон"),
			"options" => site_templates(),
			"field" => "page_template",
		),
		"menu_header" => array(
			"class" => "base::textbox",
			"size" => "100",
			"prompt" => Dreamedit::translate("Заголовок к картинке в меню"),
			"field" => "menu_header",
		),
		"menu_header_en" => array(
			"class" => "base::textbox",
			"size" => "100",
			"prompt" => Dreamedit::translate("Заголовок к картинке в меню (English)"),
			"field" => "menu_header_en",
		),
		"menu_link" => array(
			"class" => "base::editor",
			"type" => "Basic",
			"prompt" => Dreamedit::translate("Ссылка к картинке в меню"),
			"field" => "menu_link",
		),
		"menu_picture" => array(
			"class" => "base::editor",
			"prompt" => Dreamedit::translate("Картинке в меню (188 х 90)"),
			"type" => "Basic",
			"field" => "menu_picture",
		),
        "to_pwjournal" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("На сайт pwjournal.ru"),
            "value" => "0",
            "options" => "",
            "field" => "to_pwjournal",
        ),
		"status" => array(
			"class" => "base::checkbox",
			"prompt" => Dreamedit::translate("Опубликовать"),
			"value" => "1",
			"options" => "",
			"field" => "page_status",
		),
        "status_en" => array(
            "class" => "base::checkbox",
            "prompt" => Dreamedit::translate("Опубликовать (En)"),
            "value" => "1",
            "options" => "",
            "field" => "page_status_en",
        ),
        "seo_label"     => array(
            "class"  => "base::header",
            "value" => "SEO",
            "seo_open" => "1",
        ),
        "title_seo"      => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Title Russian"),
            "size" => "60",
            "field" => "title_seo",
            "buttons" => "quot",
            "seo_field" => "1",
        ),
        "title_seo_en"      => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Title English"),
            "size" => "60",
            "field" => "title_seo_en",
            "buttons" => "quot",
            "seo_field" => "1",
        ),
        "descr_seo"   => array(
            "class" => "base::textarea",
            "prompt" => Dreamedit::translate("Description"),
            "field" => "descr_seo",
            "cols" => "51",
            "rows" => "5",
            "seo_field" => "1",
        ),
        "descr_seo_en"   => array(
            "class" => "base::textarea",
            "prompt" => Dreamedit::translate("Description English"),
            "field" => "descr_seo_en",
            "cols" => "51",
            "rows" => "5",
            "seo_field" => "1",
        ),
        "keywords_seo"   => array(
            "class" => "base::textarea",
            "prompt" => Dreamedit::translate("Keywords"),
            "cols" => "51",
            "rows" => "5",
            "field" => "keywords_seo",
            "seo_field" => "1",
        ),
        "keywords_seo_en"   => array(
            "class" => "base::textarea",
            "prompt" => Dreamedit::translate("Keywords English"),
            "cols" => "51",
            "rows" => "5",
            "field" => "keywords_seo_en",
            "seo_field" => "1",
        ),
        "og_image" => array(
            "class" => "base::editor",
            "prompt" => Dreamedit::translate("Open Graph Картинка"),
            "type" => "Basic",
            "field" => "og_image",
            "seo_field" => "1",
        ),
        "og_image_en" => array(
            "class" => "base::editor",
            "prompt" => Dreamedit::translate("Open Graph Картинка English"),
            "type" => "Basic",
            "field" => "og_image_en",
            "seo_field" => "1",
        ),
        "og_video"      => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Open Graph Видео"),
            "size" => "200",
            "field" => "og_video",
            "seo_field" => "1",
        ),
        "og_video_en"      => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Open Graph Видео English"),
            "size" => "200",
            "field" => "og_video_en",
            "seo_field" => "1",
        ),
        "og_audio"      => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Open Graph Аудио"),
            "size" => "200",
            "field" => "og_audio",
            "seo_field" => "1",
        ),
        "og_audio_en"      => array(
            "class" => "base::textbox",
            "prompt" => Dreamedit::translate("Open Graph Аудио English"),
            "size" => "200",
            "field" => "og_audio_en",
            "seo_field" => "1",
        ),
	),
);


if($_CONFIG["global"]["general"]["test"])
{
	$mod_array["components"]["dell"] = array(
		"class" => "base::checkbox",
		"prompt" => Dreamedit::translate("Защищенная"),
		"value" => "0",
		"options" => "",
		"field" => "page_dell",
	);
}
?>